.TH SYSCALL\-SENSOR 1 "08 October 2018"
.SH NAME
syscall\-sensor \- a system call sensing utility
.SH SYNOPSIS
\fBsyscall\-sensor\fP [\fICOMMAND\fP] [\fIOPTIONS\fP]

\fBsyscall\-sensor\fP [\fBstatus\fP|\fBstop\fP|\fBstart\fP 
.RS 8
[\fB\-\-flags\fP=\fIFLAGS\fP] [\fB\-n \-p \-c \-f \-t \-s \-a\fP]
.br
[\fB\-o\fP \fIFILE\fP]
.br
[\fB\-\-separator=\fP\fISEP\fP]
.br
[\fB\-\-daemonize=\fP\fBON\fP|\fBOFF\fP|\fB0\fP|\fB1\fP] ]
.RE
.SH DESCRIPTION
This program traces raw system calls and logs them to a specified output file.
See OPTIONS for what data can be traced and logged.
See COMMANDS for what actions can be taken.
See DEFAULTS for the behavior when no options are set.
.SH COMMANDS
When run without a command, the program will print its usage and exit.

.SS start \fP[\fIOPTIONS\fP]
Starts tracing according to the given OPTIONS.
.br
Begins reading system call data from the trace pipe and logging it to trace.log or to the (optionally) specified output file.
.br
See section \fIOPTIONS\fP for more information on valid options for the \fBstart\fP command.

.SS stop
Stops the sensor (if it is running).
.br
Cleanly closes the open files, resets the trace pipe, clears filters, and closes the log file.


.SS status
Shows the status of the sensor.
.br
Status information includes whether the sensor is running and what data is being recorded.

.SH OPTIONS
.SS Data Field Options
.TP
\fB-n\fP
Include the name of the process in the log.
.TP
\fB-p\fP
Include the process ID for each record in the log.
.TP
\fB-c\fP
Include the CPU number of the process in the log.
.TP
\fB-f\fP
Include the field containing the values of irqs-off, needs-resched, hardirq/softirq, and preempt-depth in the log.
.TP
\fB-t\fP
Include the timestamp field for the process in the log.
.TP
\fB-s\fP
Include the number of the system call made by the process in the log.
.TP
\fB-a\fP
Include the arguments to the system call made by the process in the log.
